version: 2

models:
  - name: foo
    columns:
      - name: id
        tests:
          - unique:
              config: 
                severity: warn
  - name: bar
    columns:
      - name: id
        tests:
          - unique